name: 0.7.1.$(rev:rrrr)

trigger: none

resources:
  pipelines:
  - pipeline: etheos-ci-test
    source: etheos-ci-test
    trigger:
      branches:
        include:
        - master

variables:
- group: deploy-secrets

stages:
- stage: deploy
  displayName: 'Deploy'
  jobs:
  - job: deploy_test_image
    displayName: 'Deploy to test environment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - task: DownloadBuildArtifacts@1
      displayName: 'Download build number from etheos pipeline'
      inputs:
        buildType: 'specific'
        project: '1f2fe263-7869-4749-8f35-303d29c536e2'
        pipeline: '13'
        buildVersionToDownload: 'latestFromBranch'
        branchName: '$(Build.SourceBranch)'
        downloadType: 'single'
        artifactName: 'build_number'
        downloadPath: '$(Build.SourcesDirectory)'
    - script: |
        export ETHEOS_BUILD_NUMBER=$(cat build_number/BUILD_NUMBER)
        echo "##vso[task.setvariable variable=ETHEOS_BUILD_NUMBER;]$ETHEOS_BUILD_NUMBER"
        echo "ETHEOS_BUILD_NUMBER=$(ETHEOS_BUILD_NUMBER)"
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Set ETHEOS_BUILD_NUMBER variable from downloaded artifact

    - task: Docker@2
      inputs:
        command: login
        containerRegistry: etheos
    - script: |
        docker pull etheos.azurecr.io/etheos/dev
        docker tag etheos.azurecr.io/etheos/dev etheos.azurecr.io/etheos/test
        docker tag etheos.azurecr.io/etheos/dev etheos.azurecr.io/etheos/test:$(ETHEOS_BUILD_NUMBER)
      displayName: 'Pull etheos:dev image and tag as test'
    - task: Docker@2
      condition: succeeded()
      displayName: 'Push etheos:test image'
      inputs:
        command: push
        repository: etheos/test
        tags: |
          $(ETHEOS_BUILD_NUMBER)
          latest
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh CREATE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e test
      condition: succeeded()
      displayName: 'Deploy to test environment'
